ARG OPENCLAW_BASE_IMAGE="openclaw-runtime:local"
FROM ${OPENCLAW_BASE_IMAGE}

USER root

COPY scripts/addons-example-heartbeat.sh /opt/openclaw-addons/bin/addons-example-heartbeat
COPY config-template/supervisor.d/addons-example.conf /etc/supervisor/conf.d/addons-example.conf

RUN chmod 0755 /opt/openclaw-addons/bin/addons-example-heartbeat
